### ISSUE TITLE
Incorrect CPU usage graphed?

### ISSUE THREAD

**Issue by jperseo** [darold/sysusage#6]
I'm not sure if this my misinterpretation, or an actual error.
CPU0 distribution usage:
User: current=77.44, max=78.51, average=19.61
Nice: current=0.00, max=0.00, average=0.00
System: current=12.39, max=15.64, average=4.95

However, User and System seem inaccurate based on the sar output below.
sar -u ALL shows:

06:50:01 PM     CPU      %usr     %nice      %sys   %iowait    %steal      %irq     %soft    %guest    %gnice     %idle
07:00:01 PM     all      5.77      0.00      2.88      0.04      0.00      0.00      0.04      0.00      0.00     91.28
07:10:01 PM     all      6.17      0.00      3.09      0.02      0.00      0.00      0.05      0.00      0.00     90.67
07:20:01 PM     all      6.11      0.00      3.04      0.04      0.00      0.00      0.04      0.00      0.00     90.77
07:30:01 PM     all      6.09      0.00      3.04      0.03      0.00      0.00      0.06      0.00      0.00     90.78
07:40:01 PM     all      6.04      0.00      3.10      0.02      0.00      0.00      0.04      0.00      0.00     90.81
07:50:01 PM     all      5.89      0.00      2.86      0.02      0.00      0.00      0.04      0.00      0.00     91.20
08:00:02 PM     all      5.21      0.00      2.65      0.02      0.00      0.00      0.04      0.00      0.00     92.09
08:10:01 PM     all      5.50      0.00      2.74      0.03      0.00      0.00      0.03      0.00      0.00     91.70
Average:        all      2.22      0.00      1.70      0.06      0.00      0.00      0.02      0.00      0.00     95.99
----
Thank you.

**Comment by darold** [comment]
Hi,

You are comparing stats for CPU0 with average on all CPU, unless you have a single core the statistics differences are normal. Also by default sar has a pooling interval of 10 minutes, sysusage us a 1 minute interval, this can also explain some differences.

If you want to look at CPU0 individual stats use  `sar -P ALL -u ALL`

Regards,

**Comment by jperseo** [comment]
Hi Gilles,
Thanks for the response.  The machine I initially installed on has a single core.  Once I moved over to multi core systems, I see that sar output and graphs correlate.  Thank you for a great tool.
